backend:
  name: github
  branch: dev
  repo: cyscale/grc-cms
  site_domain: cyscale-grc-cms.netlify.app
  commit_messages:
    create: 'feat: add {{collection}} "{{slug}}"'
    update: 'fix: update {{collection}} "{{slug}}"'
    delete: 'fix: delete {{collection}} "{{slug}}"'
    uploadMedia: 'chore: upload media "{{path}}"'
    deleteMedia: 'chore: delete media "{{path}}"'
    openAuthoring: '{{message}}'

media_folder: media

collections:
  - name: queries
    label: Queries
    label_singular: Query
    folder: queries
    create: true
    extension: json
    slug: '{{fields.slug}}'
    fields:
      - { name: 'name', label: 'Name', widget: 'string' }
      - { name: 'slug', label: 'Slug', widget: 'string' }
      - {
          name: 'query',
          label: 'Query',
          widget: 'query',
          hint: 'You should copy-paste the final query from the Sandbox',
        }
  - name: controls
    label: Controls
    label_singular: Control
    folder: controls
    create: true
    editor:
      preview: false
    extension: json
    slug: '{{fields.slug}}'
    fields:
      - { name: 'name', label: 'Title', widget: 'string' }
      - {
          name: 'description',
          label: 'Issue Description',
          hint: 'Displayed on Data Security Dashboard',
          widget: 'string',
          required: false,
        }
      - { name: 'slug', label: 'Slug', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown', modes: ['raw'] }
      - label: 'Severity'
        name: 'severity'
        widget: 'select'
        options:
          - { label: 'Low', value: 1 }
          - { label: 'Medium', value: 2 }
          - { label: 'High', value: 3 }
      - name: 'remediationDescription'
        label: 'Remediation'
        widget: 'markdown'
        modes: ['raw']
      - label: 'Alert for secondary only'
        name: 'alertForSecondaryOnly'
        widget: 'boolean'
        default: false
        hint: 'Create alerts for this control only if there are other impacted assets besides the primary one'
      - label: 'Rules'
        name: 'rules'
        widget: 'list'
        summary: '{{query.value}}'
        fields:
          - label: 'Cloud Providers'
            name: 'cloudProviders'
            widget: 'select'
            multiple: true
            options:
              - { label: 'AWS', value: 'aws' }
              - { label: 'Azure', value: 'azure' }
              - { label: 'Alibaba', value: 'alibaba' }
              - { label: 'Google Cloud', value: 'gcp' }
              - { label: 'Okta', value: 'okta' }
          - label: 'Comparator'
            name: 'comparator'
            widget: 'select'
            options:
              - { label: 'Equal', value: 'eq' }
              - { label: 'Not equal', value: 'neq' }
          - label: 'Expected result'
            name: 'expectedResult'
            widget: 'select'
            options:
              - { label: 'Empty array', value: '[]' }
              - { label: 'True', value: 'true' }
              - { label: 'False', value: 'false' }
          - label: 'Subjects'
            name: 'subjects'
            widget: 'select'
            multiple: true
            options:
              [
                AccessAnalyzer,
                ActivityLogAlert,
                Alert,
                AlertPolicy,
                AMI,
                API,
                Application,
                ApplicationGateway,
                AutoProvisioningSetting,
                AutoScalingGroup,
                BigQueryTable,
                BigTable,
                BlobContainer,
                Bucket,
                CacheCluster,
                Certificate,
                CloudAccount,
                CloudSpanner,
                CloudSQLInstance,
                Cluster,
                ConfigurationRecorder,
                ContainerRegistry,
                ContainerRegistry,
                CosmosDBAccount,
                CustomDomain,
                DataStream,
                DBCluster,
                DBInstance,
                Disk,
                Domain,
                DynamodbTable,
                EBSSettings,
                ECRImage,
                ECRPublicImage,
                ECRPublicRepository,
                ECRRepository,
                ECSCluster,
                ECSContainerInstance,
                ECSScheduledTask,
                ECSService,
                ECSTask,
                ECSTaskContainer,
                ECSTaskContainerSpec,
                ECSTaskDefinition,
                ECSTaskSet,
                EventBridgeRule,
                EventBridgeSchedule,
                Firewall,
                FlowLog,
                Function,
                FunctionApp,
                FunctionService,
                Group,
                HTTPListener,
                IAMAccountSummary,
                IAMApplication,
                IAMGroup,
                IAMPasswordPolicy,
                IAMPermission,
                IAMPolicy,
                IAMRole,
                IAMServerCertificate,
                IAMServiceAccount,
                IAMServiceAccountKey,
                IAMServicePrincipal,
                IAMUser,
                IAMVirtualMFADevice,
                IdentityProvider,
                Image,
                IPConfiguration,
                KeyPair,
                KMSKey,
                KMSSecret,
                KMSVault,
                LaunchTemplate,
                LaunchTemplateVersion,
                LoadBalancer,
                LogBucket,
                LogMetric,
                LogProfile,
                LogSink,
                ManagedZone,
                MariaDBServer,
                MetricAlarm,
                MetricFilter,
                MNSQueue,
                MNSSubscription,
                MNSTopic,
                MQBroker,
                MySQLFlexibleServer,
                MySQLServer,
                NetworkACL,
                NetworkInterface,
                NetworkWatcher,
                OrgAccount,
                PasswordPolicy,
                Policy,
                PolicyAssignment,
                PostgreSQLFlexibleServer,
                PostgreSQLServer,
                PrefixList,
                Pricing,
                Project,
                PublicIP,
                PublicIP,
                PubSubLiteSubscription,
                PubSubLiteTopic,
                PubSubSubscription,
                PubSubTopic,
                RedisInstance,
                RedshiftCluster,
                SageMakerNoteBook,
                SBNamespace,
                SBQueue,
                SecurityContact,
                SecurityGroup,
                Site,
                Snapshot,
                SNSSubscription,
                SNSTopic,
                SQLDatabase,
                SQLServer,
                SQLUser,
                SQSQueue,
                SSLPolicy,
                SSOGroup,
                SSOIdentityStore,
                SSOPermissionSet,
                SSOUser,
                StorageAccount,
                StorageAccountFileShare,
                StorageAccountQueue,
                StorageAccountTable,
                Subnetwork,
                SubscriptionDiagnosticSettings,
                TargetGroup,
                TargetHTTPSProxy,
                TargetSSLProxy,
                Trail,
                Trail,
                User,
                VirtualNetwork,
                VM,
                VPC,
                VPCFlowLog,
                VPCLink,
                VPCRouteTable,
                VPNGateway,
              ]
          - label: 'Query'
            name: 'query'
            widget: 'relation'
            collection: 'queries'
            search_fields: ['slug', 'name']
            value_field: '{{slug}}'
            display_fields: ['{{slug}}: {{name}}']
          - label: 'Return path'
            name: 'returnPath'
            widget: 'string'
            hint: 'List of object keys separated by dots. e.g. `hasIAMRoles.hasIAMPolicy.hasIAMPolicyStatement`'
            required: false
  - name: policies
    label: Policies & Standards
    label_singular: Policy
    folder: policies
    create: true
    editor:
      preview: false
    extension: json
    slug: '{{fields.slug}}'
    fields:
      - { name: 'name', label: 'Name', widget: 'string' }
      - { name: 'isStandard', label: 'Standard', widget: 'boolean' }
      - { name: 'enabled', label: 'Enabled', widget: 'boolean', default: true }
      - { name: 'slug', label: 'Slug', widget: 'string' }
      - { name: 'version', label: 'Version', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown', modes: ['raw'] }
      - label: 'Procedures'
        name: 'procedures'
        widget: 'list'
        summary: '{{fields.name}}'
        fields:
          - { name: 'name', label: 'Name', widget: 'string' }
          - { name: 'slug', label: 'Slug', widget: 'string' }
          - {
              name: 'body',
              label: 'Body',
              widget: 'markdown',
              modes: ['raw'],
              required: false,
            }
          - label: 'Controls'
            name: 'controls'
            widget: 'list'
            fields:
              - label: 'Control'
                name: 'control'
                widget: 'string'
                hint: 'The control slug'
  - name: techniques
    label: Techniques
    label_singular: Technique
    folder: mitre/techniques
    create: true
    extension: json
    slug: '{{fields.mid}}'
    hide: true
    fields:
      - { name: 'mid', label: 'MID', widget: 'string' }
      - { name: 'name', label: 'Name', widget: 'string' }
      - {
          name: 'subTechniqueName',
          label: 'SubTechnique Name',
          widget: 'string',
        }
      - { name: 'link', label: 'Link', widget: 'string' }
      - { name: 'permalink', label: 'Permalink', widget: 'string' }

  - name: mappings
    label: MITRE ATT&CK Mappings
    label_singular: MITRE ATT&CK Mapping
    folder: mitre/mappings
    create: true
    extension: json
    slug: '{{fields.mid}}'
    identifier_field: display_name
    editor:
      preview: false
    fields:
      - name: 'display_name'
        label: 'Title'
        widget: 'string'
      - label: 'Technique'
        name: 'mid'
        widget: 'relation'
        collection: 'techniques'
        search_fields: ['mid', 'name']
        value_field: '{{mid}}'
        display_fields: ['{{mid}}: {{name}}']
      - label: 'Controls'
        name: 'controls'
        widget: 'list'
        allow_add: true
        label_singular: 'Control'
        hint: 'Comma-separated control slugs'
      - label: 'Propagators'
        name: 'propagators'
        widget: 'select'
        required: false
        multiple: true
        options:
          [
            AccessAnalyzer,
            ActivityLogAlert,
            Alert,
            AlertPolicy,
            AMI,
            API,
            Application,
            ApplicationGateway,
            AutoProvisioningSetting,
            AutoScalingGroup,
            BigQueryTable,
            BigTable,
            BlobContainer,
            Bucket,
            CacheCluster,
            Certificate,
            CloudAccount,
            CloudSpanner,
            CloudSQLInstance,
            Cluster,
            ConfigurationRecorder,
            ContainerRegistry,
            ContainerRegistry,
            CosmosDBAccount,
            CustomDomain,
            DataStream,
            DBCluster,
            DBInstance,
            Disk,
            Domain,
            DynamodbTable,
            EBSSettings,
            ECRImage,
            ECRPublicImage,
            ECRPublicRepository,
            ECRRepository,
            ECSCluster,
            ECSContainerInstance,
            ECSScheduledTask,
            ECSService,
            ECSTask,
            ECSTaskContainer,
            ECSTaskContainerSpec,
            ECSTaskDefinition,
            ECSTaskSet,
            EventBridgeRule,
            EventBridgeSchedule,
            Firewall,
            FlowLog,
            Function,
            FunctionApp,
            FunctionService,
            Group,
            HTTPListener,
            IAMAccountSummary,
            IAMApplication,
            IAMGroup,
            IAMPasswordPolicy,
            IAMPermission,
            IAMPolicy,
            IAMRole,
            IAMServerCertificate,
            IAMServiceAccount,
            IAMServiceAccountKey,
            IAMServicePrincipal,
            IAMUser,
            IAMVirtualMFADevice,
            IdentityProvider,
            Image,
            IPConfiguration,
            KeyPair,
            KMSKey,
            KMSSecret,
            KMSVault,
            LaunchTemplate,
            LaunchTemplateVersion,
            LoadBalancer,
            LogBucket,
            LogMetric,
            LogProfile,
            LogSink,
            ManagedZone,
            MariaDBServer,
            MetricAlarm,
            MetricFilter,
            MNSQueue,
            MNSSubscription,
            MNSTopic,
            MQBroker,
            MySQLFlexibleServer,
            MySQLServer,
            NetworkACL,
            NetworkInterface,
            NetworkWatcher,
            OrgAccount,
            PasswordPolicy,
            Policy,
            PolicyAssignment,
            PostgreSQLFlexibleServer,
            PostgreSQLServer,
            PrefixList,
            Pricing,
            Project,
            PublicIP,
            PublicIP,
            PubSubLiteSubscription,
            PubSubLiteTopic,
            PubSubSubscription,
            PubSubTopic,
            RedisInstance,
            RedshiftCluster,
            SageMakerNoteBook,
            SBNamespace,
            SBQueue,
            SecurityContact,
            SecurityGroup,
            Site,
            Snapshot,
            SNSSubscription,
            SNSTopic,
            SQLDatabase,
            SQLServer,
            SQLUser,
            SQSQueue,
            SSLPolicy,
            SSOGroup,
            SSOIdentityStore,
            SSOPermissionSet,
            SSOUser,
            StorageAccount,
            StorageAccountFileShare,
            StorageAccountQueue,
            StorageAccountTable,
            Subnetwork,
            SubscriptionDiagnosticSettings,
            TargetGroup,
            TargetHTTPSProxy,
            TargetSSLProxy,
            Trail,
            Trail,
            User,
            VirtualNetwork,
            VM,
            VPC,
            VPCFlowLog,
            VPCLink,
            VPCRouteTable,
            VPNGateway,
          ]
      - label: 'Assets'
        name: 'assets'
        widget: 'select'
        multiple: true
        options:
          [
            AccessAnalyzer,
            ActivityLogAlert,
            Alert,
            AlertPolicy,
            AMI,
            API,
            Application,
            ApplicationGateway,
            AutoProvisioningSetting,
            AutoScalingGroup,
            BigQueryTable,
            BigTable,
            BlobContainer,
            Bucket,
            CacheCluster,
            Certificate,
            CloudAccount,
            CloudSpanner,
            CloudSQLInstance,
            Cluster,
            ConfigurationRecorder,
            ContainerRegistry,
            ContainerRegistry,
            CosmosDBAccount,
            CustomDomain,
            DataStream,
            DBCluster,
            DBInstance,
            Disk,
            Domain,
            DynamodbTable,
            EBSSettings,
            ECRImage,
            ECRPublicImage,
            ECRPublicRepository,
            ECRRepository,
            ECSCluster,
            ECSContainerInstance,
            ECSScheduledTask,
            ECSService,
            ECSTask,
            ECSTaskContainer,
            ECSTaskContainerSpec,
            ECSTaskDefinition,
            ECSTaskSet,
            EventBridgeRule,
            EventBridgeSchedule,
            Firewall,
            FlowLog,
            Function,
            FunctionApp,
            FunctionService,
            Group,
            HTTPListener,
            IAMAccountSummary,
            IAMApplication,
            IAMGroup,
            IAMPasswordPolicy,
            IAMPermission,
            IAMPolicy,
            IAMRole,
            IAMServerCertificate,
            IAMServiceAccount,
            IAMServiceAccountKey,
            IAMServicePrincipal,
            IAMUser,
            IAMVirtualMFADevice,
            IdentityProvider,
            Image,
            IPConfiguration,
            KeyPair,
            KMSKey,
            KMSSecret,
            KMSVault,
            LaunchTemplate,
            LaunchTemplateVersion,
            LoadBalancer,
            LogBucket,
            LogMetric,
            LogProfile,
            LogSink,
            ManagedZone,
            MariaDBServer,
            MetricAlarm,
            MetricFilter,
            MNSQueue,
            MNSSubscription,
            MNSTopic,
            MQBroker,
            MySQLFlexibleServer,
            MySQLServer,
            NetworkACL,
            NetworkInterface,
            NetworkWatcher,
            OrgAccount,
            PasswordPolicy,
            Policy,
            PolicyAssignment,
            PostgreSQLFlexibleServer,
            PostgreSQLServer,
            PrefixList,
            Pricing,
            Project,
            PublicIP,
            PublicIP,
            PubSubLiteSubscription,
            PubSubLiteTopic,
            PubSubSubscription,
            PubSubTopic,
            RedisInstance,
            RedshiftCluster,
            SageMakerNoteBook,
            SBNamespace,
            SBQueue,
            SecurityContact,
            SecurityGroup,
            Site,
            Snapshot,
            SNSSubscription,
            SNSTopic,
            SQLDatabase,
            SQLServer,
            SQLUser,
            SQSQueue,
            SSLPolicy,
            SSOGroup,
            SSOIdentityStore,
            SSOPermissionSet,
            SSOUser,
            StorageAccount,
            StorageAccountFileShare,
            StorageAccountQueue,
            StorageAccountTable,
            Subnetwork,
            SubscriptionDiagnosticSettings,
            TargetGroup,
            TargetHTTPSProxy,
            TargetSSLProxy,
            Trail,
            Trail,
            User,
            VirtualNetwork,
            VM,
            VPC,
            VPCFlowLog,
            VPCLink,
            VPCRouteTable,
            VPNGateway,
          ]
