name: Deploy to dev

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - queries/**
  #     - controls/**

  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Semantic Release
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Semantic Release'
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: true
  deploy:
    runs-on: ubuntu-latest
    name: Deploy GRC to dev
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Copy
        env:
          AZ_ST_CONN_STRING: ${{ secrets.DEV_AZ_ST_CONN_STRING }}
        uses: azure/CLI@v1
        with:
          azcliversion: 2.37.0
          inlineScript: |
            az storage blob upload-batch --connection-string $(echo "$AZ_ST_CONN_STRING" | base64 -d) --destination grc/queries --source ./queries --overwrite
            az storage blob upload-batch --connection-string $(echo "$AZ_ST_CONN_STRING" | base64 -d) --destination grc/controls --source ./controls --overwrite
      - name: Delete old entries (unmodified within the last 2 minutes)
        env:
          AZ_ST_CONN_STRING: ${{ secrets.DEV_AZ_ST_CONN_STRING }}
        uses: azure/CLI@v1
        with:
          azcliversion: 2.37.0
          inlineScript: |
            modified_since=$(date --utc -d "-2 min" "+%Y-%m-%dT%H:%MZ")
            az storage blob delete-batch -s grc --connection-string $(echo "$AZ_ST_CONN_STRING" | base64 -d) --pattern 'queries/*' --if-unmodified-since $modified_since
            az storage blob delete-batch -s grc --connection-string $(echo "$AZ_ST_CONN_STRING" | base64 -d) --pattern 'controls/*' --if-unmodified-since $modified_since
      - name: Update
        shell: bash
        env:
          BAPI_GRC_UPDATE_ENDPOINT: ${{ secrets.DEV_BAPI_GRC_UPDATE_ENDPOINT }}
          INTERNAL_API_KEY: ${{ secrets.DEV_INTERNAL_API_KEY }}
        run: |
          curl --silent --show-error --fail -X POST $BAPI_GRC_UPDATE_ENDPOINT -H "Content-Type:application/json" -H "x-api-key:$(echo "$INTERNAL_API_KEY" | base64 -d)" -d '{"accounts":"all"}'
