name: Deploy to prod

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy GRC to prod
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
      - name: Login
        uses: azure/login@v1
        with:
          subscription-id: ${{ vars.AZ_SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.AZ_TENANT_ID }}
          client-id: ${{ vars.AZ_CLIENT_ID }}
      - name: Deploy
        uses: azure/cli@v1
        with:
          azcliversion: 2.37.0
          inlineScript: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              if ! [[ "$file" =~ ^controls*|^queries* ]]; then
                continue
              fi

              az storage blob upload -c grc --file $file --name $file --overwrite --metadata slug=$(cat $file | jq -r '.slug') --auth-mode login
            done

            for file in ${{ steps.changed-files.outputs.deleted_files }}; do
              if ! [[ "$file" =~ ^controls*|^queries* ]]; then
                continue
              fi

              az storage blob delete -c grc --name $file --auth-mode login
            done
