name: Deploy to prod

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Semantic Release
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Semantic Release'
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: true
  deploy:
    runs-on: ubuntu-latest
    name: Deploy GRC to prod
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            queries/**
            controls/**
            policies/**
            mitre/**
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.GRC_CMS_UPLOAD_ROLE_ARN }}
          aws-region: ${{ vars.GRC_BUCKET_REGION }}
      - name: Deploy
        run: |
          # Handle GRC queries
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            aws s3 cp $file s3://${{ vars.S3_BUCKET_NAME }}/$file
          done

          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            aws s3 rm s3://${{ vars.S3_BUCKET_NAME }}/$file
          done
